name: 'redfield&sons'
favicon: null
layout_spectrum: 0.8954313972499222
typography_spectrum: 0.3951965239830315
title: motherofadventure
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4747714411932975
  lightness: 0.06691548880189657
  saturation: 0.5141344480216503
  rhythmicContrast: 0.7757920098956674
purpose: []
