name: 'redfield&sons'
favicon: null
layout_spectrum: 0.75243
typography_spectrum: 0.28892
title: motherofadventure
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#34373c'
    - '#9a9a8d'
    - '#c0cd9a'
  brandStrength: 0.4747714411932975
  lightness: 0.06691548880189657
  saturation: 0.5141344480216503
  rhythmicContrast: 0.7757920098956674
purpose: []
